version: '2.1'
services:
  encountergen:
    build:
      context: docker/encountergen
    networks:
      - encountergen
    volumes:
      - "./app:/encountergen"
      - "./ux:/encountergenux"
    ports:
      # [Port on host]:[Port inside container]
      - "5000:80"

networks:
  encountergen: